package org.randi3.configuration

object ConfigurationValues extends Enumeration{

  val MAIL_SERVER, MAIL_PORT, MAIL_FROM, MAIL_SMTP_AUTH, MAIL_USERNAME, MAIL_PASSWORD, MAIL_SSL, DB_TYPE, DB_ADDRESS, DB_USER, DB_PASSWORD, DB_NAME, LOGFILE_PATH, PLUGIN_PATH, INITIAL_OBJECTS_CREATED = Value
}